#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100. (fizzbuzz.fizz,buzz)
NUMBER=1
while((NUMBER<=100));do
	if [  "$((NUMBER%3))" -eq 0  ] &&  [ "$((NUMBER%5))" -eq 0  ] ;then
		echo "FizzBuzz"
	elif [ "$((NUMBER%3))" -eq 0 ] ;then
		echo "Fizz"
	elif [ "$((NUMBER%5))" -eq 0 ] ;then
		echo "Buzz"
	else 
		echo "$NUMBER"
	fi
((NUMBER++))
done;
