#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
number=1
while [ $number -lt 11 ]; do
  echo "Best School"
  if [ $number -eq 9 ]; then
    echo "Hi"
  fi
  ((number++))
done
