#!/usr/bin/env bash
# will display Best School 10 times
number=1
while [ $number -lt 9 ]; do
  echo "Best School"
  if [ $number -eq 6 ]; then
    echo "good luck"
elif [ $number -eq 3 ]; then
 echo "bad luck"
  fi

  ((number++))
done

