#!/usr/bin/env bash
# will display Best School 10 times
number=1
while ((number<11));do
  if [ $number -eq 8 ]; then
    echo "good luck"
elif [ $number -eq 4 ]; then
 echo "bad luck"
else
	echo "Best School"
  fi

  ((number++))
done

