#!/usr/bin/env bash
#Write a Bash script that displays: The content of the current directory In a list format Where only the part of the name after the first dash is displayed (refer to the exampple)

FILES=$(ls)
for i in $FILES; do
  NEW=$(find . -maxdepth 1 -name "$i" | cut -d "/" -f2 | cut -d "-" -f2)
  echo "$NEW"
done



