#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.Requirements:You must use if and, else (case is forbidden) Your Bash script should check if the file exists and print:if the file exists: school file exists if the file does not exist: school file does not exist If the file exists, print:if the file is empty: school file is empty if the file is not empty: school file is not empty if the file is a regular file: school is a regular file i the file is not a regular file: (nothing)
FILE=$( find . -name "school" |cut -d "/" -f2)
if [ -e "$FILE" ] ;then
	echo "school file exists"
	if [ -s "$FILE" ] ;then
		echo "school file is not empty"
	elif [ ! -s "$FILE" ] ;then
		echo "school file is empty"
	fi
	if [ -f "$FILE" ] ;then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
