#!/usr/bin/env bash
# A script that displays a list of the currently running processes
echo "USER   PID %CPU %MEM VSZ RSS TTY  STAT  START  TIME  COMMAND"
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest






