#!/usr/bin/env bash
#Process and PID
touch /var/run/myscript.pid

trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 1
done
