#!/usr/bin/env bash
#kil command
trap 'echo "Stopping the script..."; exit' SIGINT

count=0

while true; do
    echo "To infinity and beyond"
    sleep 2
    count=$((count + 1))
    if [ $count -eq 6 ]; then

        kill -s SIGTERM $$
        exit
    fi
done
