#!/usr/bin/env bash
#kill command
trap 'echo "Stopping the script..."; exit' SIGINT

count=0

while true; do
    echo "To infinity and beyond"
    sleep 2
    count=$((count + 1))
    if [ $count -eq 6 ]; then
        # Get the process ID of the current script
        pid=$$
        # Kill the process with SIGTERM
        kill -s SIGTERM "$pid"
        exit
    fi
done
